# Generated by Django 5.2 on 2025-04-08 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'specialization',
                    models.CharField(
                        choices=[
                            ('D', 'Веб-разработка на Django'),
                            ('M', 'Машинное обучение'),
                            ('B', 'Большие данные'),
                            ('G', 'Веб-разработка на Go'),
                            ('A', 'Анализ данных'),
                        ],
                        default='D',
                    ),
                ),
                (
                    'rating',
                    models.PositiveSmallIntegerField(
                        choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')]
                    ),
                ),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
