# Generated by Django 5.2 on 2025-04-25 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(
                help_text='Содержание отзыва (максимальная длина не ограничена)', verbose_name='Текст отзыва'
            ),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, help_text='Дата и время создания отзыва', verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')],
                help_text='Оценка курса от 1 (ужасно) до 5 (отлично)',
                verbose_name='Оценка',
            ),
        ),
        migrations.AlterField(
            model_name='review',
            name='specialization',
            field=models.CharField(
                choices=[
                    ('D', 'Веб-разработка на Django'),
                    ('M', 'Машинное обучение'),
                    ('B', 'Большие данные'),
                    ('G', 'Веб-разработка на Go'),
                    ('A', 'Анализ данных'),
                ],
                default='D',
                help_text='Направление обучения, к которому относится отзыв',
                max_length=50,
                verbose_name='Специализация',
            ),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text='Дата и время последнего обновления отзыва',
                verbose_name='Дата обновления',
            ),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(
                blank=True,
                help_text='Автор отзыва (может быть анонимным)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь',
            ),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['specialization'], name='reviews_rev_special_05da34_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='reviews_rev_rating_2db6dd_idx'),
        ),
    ]
