# Generated by Django 5.2 on 2025-04-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='specialization',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('U', 'Лайк'), ('D', 'Дизлайк')], default='U', max_length=1),
            preserve_default=False,
        ),
    ]
