# Generated by Django 5.2 on 2025-04-25 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('interactions', '0003_comment_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'default_related_name': 'votes', 'verbose_name': 'Голос', 'verbose_name_plural': 'Голоса'},
        ),
        migrations.AlterField(
            model_name='vote',
            name='content_type',
            field=models.ForeignKey(
                help_text='Тип контента, с которым происходит взаимодействие',
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype',
                verbose_name='Тип контента',
            ),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, help_text='Дата и время создания взаимодействия', verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='vote',
            name='object_id',
            field=models.PositiveIntegerField(help_text='ID объекта контента', verbose_name='ID объекта'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(
                help_text='Пользователь, взаимодействующий с контентом',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь',
            ),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(
                choices=[('U', 'Лайк'), ('D', 'Дизлайк')],
                help_text='Тип реакции пользователя (лайк или дизлайк)',
                max_length=1,
                verbose_name='Тип голоса',
            ),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
