# Generated by Django 5.2 on 2025-04-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usercourse_specialization'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usercourse',
            name='unique_user_specialization',
        ),
        migrations.AddConstraint(
            model_name='usercourse',
            constraint=models.UniqueConstraint(
                fields=('user', 'specialization'),
                name='unique_course_user_specialization',
                violation_error_message='User already has this course specialization',
            ),
        ),
    ]
