# Generated by Django 5.2 on 2025-04-17 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_usercourse_unique_user_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ban_reason',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('guest', 'Гость'),
                    ('student', 'Ученик'),
                    ('moderator', 'Модератор'),
                    ('mentor', 'Ментор'),
                    ('lead', 'Лид'),
                    ('admin', 'Админ'),
                ],
                db_index=True,
                default='guest',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                validators=[django.core.validators.RegexValidator('^@[a-zA-Z0-9_]{5,32}$')],
            ),
        ),
    ]
