# Generated by Django 5.2 on 2025-04-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0006_sticker_file_id_from_tg_alter_sticker_image_for_tg'),
        ('users', '0003_remove_usercourse_unique_user_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='featured_stickers',
            field=models.ManyToManyField(to='stickers.sticker'),
        ),
    ]
