# Generated by Django 5.2 on 2025-04-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_ban_ends_at_user_ban_reason_user_banned_at_and_more'),
        ('users', '0004_userprofile_featured_stickers'),
    ]

    operations = []
