# Generated by Django 5.2 on 2025-04-07 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='LMSCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('events_count', models.IntegerField(default=0)),
                ('visited_attendances_count', models.IntegerField(default=0)),
                (
                    'status',
                    models.CharField(
                        choices=[('enrolled', 'Enrolled'), ('graduated', 'Graduated'), ('dropped', 'Dropped')],
                        max_length=20,
                    ),
                ),
                ('certificate_id', models.IntegerField(blank=True, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('accessibility_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LMSProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_profile_id', models.IntegerField(unique=True)),
                ('uid', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('last_name', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('display_name', models.CharField(max_length=255)),
                ('avatar', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('city', models.CharField(blank=True, max_length=100)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('school_class', models.CharField(blank=True, max_length=50)),
                ('tags', models.JSONField(default=list)),
                ('clubs', models.JSONField(default=list)),
                ('competitions', models.JSONField(default=list)),
                ('public_key', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LMSGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                (
                    'course',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name='group', to='mocklms.lmscourse'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='lmscourse',
            name='profile',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='mocklms.lmsprofile'
            ),
        ),
        migrations.CreateModel(
            name='LMSTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('avatar', models.CharField(blank=True, max_length=255)),
                (
                    'course',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='teachers_list',
                        to='mocklms.lmscourse',
                    ),
                ),
            ],
        ),
    ]
