# Generated by Django 5.1.7 on 2025-04-06 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StickerPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='name')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stickers/', verbose_name='sticker_image')),
                ('decryption', models.TextField(verbose_name='decryption')),
                ('emoji', models.CharField(verbose_name='emoji')),
                ('stickerpack', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sticker', to='stickers.stickerpack')),
            ],
        ),
    ]
