# Generated by Django 5.1.7 on 2025-04-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0002_remove_sticker_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickerpack',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
    ]
