# Generated by Django 5.1.7 on 2025-04-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0003_alter_stickerpack_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='image_for_tg',
            field=models.ImageField(null=True, upload_to='stickers/for_tg/', verbose_name='sticker_image'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='image',
            field=models.ImageField(upload_to='stickers/just_img/', verbose_name='sticker_image'),
        ),
    ]
