# Generated by Django 5.1.7 on 2025-04-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0004_sticker_image_for_tg_alter_sticker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickerpack',
            name='published_on_tg',
            field=models.BooleanField(default=False, verbose_name='published_on_tg'),
        ),
    ]
