# Generated by Django 5.2 on 2025-04-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0005_stickerpack_published_on_tg'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='file_id_from_tg',
            field=models.CharField(blank=True, null=True, verbose_name='file_id_from_tg'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='image_for_tg',
            field=models.ImageField(blank=True, upload_to='stickers/for_tg/', verbose_name='sticker_image'),
        ),
    ]
