# Generated by Django 5.2 on 2025-04-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0006_sticker_file_id_from_tg_alter_sticker_image_for_tg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='decryption',
            field=models.TextField(blank=True),
        ),
    ]
