# Generated by Django 5.2 on 2025-04-25 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0007_alter_sticker_decryption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sticker',
            options={'ordering': ['stickerpack', 'id'], 'verbose_name': 'Стикер', 'verbose_name_plural': 'Стикеры'},
        ),
        migrations.AlterModelOptions(
            name='stickerpack',
            options={'ordering': ['name'], 'verbose_name': 'Набор стикеров', 'verbose_name_plural': 'Наборы стикеров'},
        ),
        migrations.AddField(
            model_name='stickerpack',
            name='normalized_name',
            field=models.CharField(
                default='',
                editable=False,
                help_text='Автоматически генерируемая нормализованная версия названия',
                max_length=255,
                unique=True,
                verbose_name='Нормализованное название',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sticker',
            name='decryption',
            field=models.TextField(
                blank=True,
                help_text='Текстовое описание или ключевые слова для стикера',
                verbose_name='Описание стикера',
            ),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='file_id_from_tg',
            field=models.CharField(
                blank=True,
                help_text='Уникальный идентификатор стикера в Telegram после публикации',
                max_length=100,
                null=True,
                verbose_name='ID файла в Telegram',
            ),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='image',
            field=models.ImageField(
                help_text='Основное изображение стикера (рекомендуемый размер: 512x512 px)',
                upload_to='stickers/just_img/',
                verbose_name='Изображение стикера',
            ),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='image_for_tg',
            field=models.ImageField(
                blank=True,
                help_text='Оптимизированная версия стикера для Telegram (формат WEBP, размер до 512 KB)',
                upload_to='stickers/for_tg/',
                verbose_name='Изображение для Telegram',
            ),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='stickerpack',
            field=models.ForeignKey(
                default=None,
                help_text='Набор, к которому принадлежит этот стикер',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='stickers',
                to='stickers.stickerpack',
                verbose_name='Набор стикеров',
            ),
        ),
        migrations.AlterField(
            model_name='stickerpack',
            name='name',
            field=models.CharField(
                help_text='Уникальное название объекта (макс. 100 символов)', max_length=100, verbose_name='Название'
            ),
        ),
        migrations.AlterField(
            model_name='stickerpack',
            name='published_on_tg',
            field=models.BooleanField(
                default=False,
                help_text='Отметьте, если набор опубликован в Telegram',
                verbose_name='Опубликовано в Telegram',
            ),
        ),
        migrations.AlterField(
            model_name='stickerpack',
            name='slug',
            field=models.SlugField(
                help_text='Уникальная часть URL для этого объекта (макс. 100 символов)',
                max_length=100,
                unique=True,
                verbose_name='URL-идентификатор',
            ),
        ),
    ]
