# Generated by Django 5.2 on 2025-04-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0008_alter_sticker_options_alter_stickerpack_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickerpack',
            name='normalized_name',
        ),
        migrations.AlterField(
            model_name='stickerpack',
            name='name',
            field=models.CharField(
                help_text='Уникальное название набора стикеров', max_length=100, verbose_name='Название набора'
            ),
        ),
        migrations.AlterField(
            model_name='stickerpack',
            name='slug',
            field=models.SlugField(
                help_text='Уникальная часть URL для набора стикеров (только латинские буквы, цифры, дефисы и подчёркивания)',
                max_length=100,
                unique=True,
                verbose_name='URL-идентификатор',
            ),
        ),
    ]
