# Generated by Django 5.2 on 2025-04-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_answerreport_topicreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicreport',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='topicreport',
            name='topic',
        ),
        migrations.DeleteModel(
            name='AnswerReport',
        ),
        migrations.DeleteModel(
            name='TopicReport',
        ),
    ]
