# Generated by Django 5.2 on 2025-04-24 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_remove_topicreport_reporter_remove_topicreport_topic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, max_length=1000, verbose_name='жалоба')),
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='Дата поступления жалобы.',
                        null=True,
                        verbose_name='дата поступления жалобы',
                    ),
                ),
                (
                    'answer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='forum.answer', verbose_name='ответ'
                    ),
                ),
                (
                    'reporter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='жалующийся',
                    ),
                ),
            ],
            options={
                'verbose_name': 'жалоба на ответ',
                'verbose_name_plural': 'жалобы на ответы',
            },
        ),
        migrations.CreateModel(
            name='TopicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, max_length=1000, verbose_name='жалоба')),
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='Дата поступления жалобы.',
                        null=True,
                        verbose_name='дата поступления жалобы',
                    ),
                ),
                (
                    'reporter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='жалующийся',
                    ),
                ),
                (
                    'topic',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='forum.topic', verbose_name='топик'
                    ),
                ),
            ],
            options={
                'verbose_name': 'жалоба на топик',
                'verbose_name_plural': 'жалобы на топики',
            },
        ),
    ]
