# Generated by Django 5.2 on 2025-04-25 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_answerreport_topicreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='answerreport',
            options={'verbose_name': 'Жалоба на ответ', 'verbose_name_plural': 'Жалобы на ответы'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Топик', 'verbose_name_plural': 'Топики'},
        ),
        migrations.AlterModelOptions(
            name='topicreport',
            options={'verbose_name': 'Жалоба на топик', 'verbose_name_plural': 'Жалобы на топики'},
        ),
        migrations.AlterModelOptions(
            name='topicview',
            options={'verbose_name': 'Просмотр топика', 'verbose_name_plural': 'Просмотры топиков'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, help_text='Дата и время создания ответа', null=True, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='answer',
            name='downvotes',
            field=models.ManyToManyField(
                blank=True,
                help_text='Пользователи, проголосовавшие против ответа',
                related_name='downvotes',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Голоса "против"',
            ),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(
                help_text='Содержание ответа (макс. 1000 символов)', max_length=1000, verbose_name='Текст ответа'
            ),
        ),
        migrations.AlterField(
            model_name='answer',
            name='topic',
            field=models.ForeignKey(
                help_text='Топик, к которому относится ответ',
                on_delete=django.db.models.deletion.CASCADE,
                to='forum.topic',
                verbose_name='Топик',
            ),
        ),
        migrations.AlterField(
            model_name='answer',
            name='upvotes',
            field=models.ManyToManyField(
                blank=True,
                help_text='Пользователи, проголосовавшие за ответ',
                related_name='upvotes',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Голоса "за"',
            ),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(
                help_text='Пользователь, оставивший ответ',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Автор',
            ),
        ),
        migrations.AlterField(
            model_name='answerreport',
            name='answer',
            field=models.ForeignKey(
                help_text='Ответ, на который поступила жалоба',
                on_delete=django.db.models.deletion.CASCADE,
                to='forum.answer',
                verbose_name='Ответ',
            ),
        ),
        migrations.AlterField(
            model_name='answerreport',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True,
                help_text='Дата и время подачи жалобы',
                null=True,
                verbose_name='Дата создания жалобы',
            ),
        ),
        migrations.AlterField(
            model_name='answerreport',
            name='reason',
            field=models.TextField(
                blank=True,
                help_text='Подробное описание причины жалобы (макс. 1000 символов)',
                max_length=1000,
                verbose_name='Причина жалобы',
            ),
        ),
        migrations.AlterField(
            model_name='answerreport',
            name='reporter',
            field=models.ForeignKey(
                help_text='Пользователь, отправивший жалобу',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Автор жалобы',
            ),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, help_text='Дата и время создания топика', null=True, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.TextField(
                help_text='Содержание топика (макс. 1000 символов)', max_length=1000, verbose_name='Текст топика'
            ),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(
                help_text='Название топика (макс. 256 символов)', max_length=256, null=True, verbose_name='Заголовок'
            ),
        ),
        migrations.AlterField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(
                help_text='Пользователь, создавший топик',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Автор',
            ),
        ),
        migrations.AlterField(
            model_name='topicreport',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True,
                help_text='Дата и время подачи жалобы',
                null=True,
                verbose_name='Дата создания жалобы',
            ),
        ),
        migrations.AlterField(
            model_name='topicreport',
            name='reason',
            field=models.TextField(
                blank=True,
                help_text='Подробное описание причины жалобы (макс. 1000 символов)',
                max_length=1000,
                verbose_name='Причина жалобы',
            ),
        ),
        migrations.AlterField(
            model_name='topicreport',
            name='reporter',
            field=models.ForeignKey(
                help_text='Пользователь, отправивший жалобу',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Автор жалобы',
            ),
        ),
        migrations.AlterField(
            model_name='topicreport',
            name='topic',
            field=models.ForeignKey(
                help_text='Топик, на который поступила жалоба',
                on_delete=django.db.models.deletion.CASCADE,
                to='forum.topic',
                verbose_name='Топик',
            ),
        ),
        migrations.AlterField(
            model_name='topicview',
            name='topic',
            field=models.ForeignKey(
                help_text='Просматриваемый топик',
                on_delete=django.db.models.deletion.CASCADE,
                to='forum.topic',
                verbose_name='Топик',
            ),
        ),
        migrations.AlterField(
            model_name='topicview',
            name='user',
            field=models.ForeignKey(
                help_text='Пользователь, просмотревший топик',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь',
            ),
        ),
    ]
