# Generated by Django 5.2 on 2025-04-25 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_status', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstatus',
            options={
                'ordering': ['-last_activity'],
                'verbose_name': 'Статус пользователя',
                'verbose_name_plural': 'Статусы пользователей',
            },
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='last_activity',
            field=models.DateTimeField(
                auto_now=True,
                help_text='Дата и время последней активности пользователя',
                verbose_name='Последняя активность',
            ),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='user',
            field=models.OneToOneField(
                help_text='Связь с пользовательской моделью',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='status',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь',
            ),
        ),
    ]
